name: Unit tests

on: [pull_request, workflow_call]

jobs:
  run-unit-tests-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-tests-results
          path: test-report.html
          retention-days: 30
